import {
  BarChart3,
  Briefcase,
  CheckSquare,
  Clock,
  CreditCard,
  FileText,
  Gift,
  GraduationCap,
  Headset,
  Heart,
  House,
  Laptop,
  Megaphone,
  Palmtree,
  PoundSterling,
  RefreshCw,
  Rocket,
  Settings,
  Target,
  Users,
} from "lucide-react";

export const data = {
  navMain: [
    {
      title: "Dashboard",
      url: "/home",
      icon: House,
    },
    {
      label: "Workforce",
    },
    {
      title: "People",
      url: "#",
      icon: Users,
      isActive: true,
      items: [
        { title: "Employees", url: "/people/employees", circleColor: "bg-primary" },
        { title: "Organisation", url: "/people/organisation", circleColor: "bg-yellow-500" },
        { title: "Departments", url: "/people/departments", circleColor: "bg-cyan-500" },
        { title: "Positions", url: "/people/positions", circleColor: "bg-green-600" },
        { title: "Documents", url: "/people/documents", circleColor: "bg-violet-600" },
      ],
    },
    {
      title: "Time & Attendance",
      url: "#",
      icon: Clock,
      isActive: true,
      items: [
        { title: "Attendance", url: "/attendance", circleColor: "bg-primary" },
        { title: "Timesheets", url: "/attendance/timesheets", circleColor: "bg-yellow-500" },
        { title: "Shifts", url: "/attendance/shifts", circleColor: "bg-cyan-500" },
        { title: "Overtime", url: "/attendance/overtime", circleColor: "bg-red-500" },
      ],
    },
    {
      title: "Leave",
      url: "#",
      icon: Palmtree,
      isActive: true,
      items: [
        { title: "Requests", url: "/leave/requests", circleColor: "bg-primary" },
        { title: "Calendar", url: "/leave/calendar", circleColor: "bg-yellow-500" },
        { title: "Balances", url: "/leave/balances", circleColor: "bg-green-600" },
        { title: "Holidays", url: "/leave/holidays", circleColor: "bg-cyan-500" },
      ],
    },
    {
      label: "Payroll & Expenses",
    },
    {
      title: "Payroll",
      url: "#",
      icon: PoundSterling,
      isActive: true,
      items: [
        { title: "Payroll Runs", url: "/payroll/runs", circleColor: "bg-primary" },
        { title: "Salaries", url: "/payroll/salaries", circleColor: "bg-yellow-500" },
        { title: "Payslips", url: "/payroll/payslips", circleColor: "bg-green-600" },
        { title: "Payslip Template", url: "/payroll/payslip-template", circleColor: "bg-violet-600" },
        { title: "Earnings", url: "/payroll/earnings", circleColor: "bg-cyan-500" },
        { title: "Deductions", url: "/payroll/deductions", circleColor: "bg-red-500" },
      ],
    },
    {
      title: "Expenses",
      url: "/expenses",
      icon: CreditCard,
    },
    {
      label: "Talent",
    },
    {
      title: "Performance",
      url: "#",
      icon: Target,
      isActive: true,
      items: [
        { title: "Goals", url: "/performance/goals", circleColor: "bg-primary" },
        { title: "Reviews", url: "/performance/reviews", circleColor: "bg-yellow-500" },
        { title: "Appraisals", url: "/performance/appraisals", circleColor: "bg-green-600" },
        { title: "Feedback", url: "/performance/feedback", circleColor: "bg-cyan-500" },
      ],
    },
    {
      title: "Learning",
      url: "#",
      icon: GraduationCap,
      isActive: true,
      items: [
        { title: "Courses", url: "/learning/courses", circleColor: "bg-primary" },
        { title: "Training", url: "/learning/training", circleColor: "bg-yellow-500" },
        { title: "Skills", url: "/learning/skills", circleColor: "bg-green-600" },
        { title: "Certifications", url: "/learning/certifications", circleColor: "bg-cyan-500" },
      ],
    },
    {
      title: "Recruitment",
      url: "#",
      icon: Briefcase,
      isActive: true,
      items: [
        { title: "Jobs", url: "/recruitment/jobs", circleColor: "bg-primary" },
        { title: "Candidates", url: "/recruitment/candidates", circleColor: "bg-yellow-500" },
        { title: "Pipeline", url: "/recruitment/pipeline", circleColor: "bg-green-600" },
        { title: "Interviews", url: "/recruitment/interviews", circleColor: "bg-cyan-500" },
        { title: "Offers", url: "/recruitment/offers", circleColor: "bg-red-500" },
      ],
    },
    {
      title: "Onboarding",
      url: "/onboarding",
      icon: Rocket,
    },
    {
      label: "Engagement",
    },
    {
      title: "Engagement",
      url: "/engagement",
      icon: Heart,
    },
    {
      title: "Benefits",
      url: "/benefits",
      icon: Gift,
    },
    {
      title: "Assets",
      url: "/assets",
      icon: Laptop,
    },
    {
      title: "Employee Lifecycle",
      url: "#",
      icon: RefreshCw,
      isActive: true,
      items: [
        { title: "Promotions", url: "/lifecycle/promotions", circleColor: "bg-primary" },
        { title: "Transfers", url: "/lifecycle/transfers", circleColor: "bg-yellow-500" },
        { title: "Disciplinary", url: "/lifecycle/disciplinary", circleColor: "bg-red-500" },
        { title: "Termination", url: "/lifecycle/termination", circleColor: "bg-red-600" },
        { title: "Offboarding", url: "/lifecycle/offboarding", circleColor: "bg-cyan-500" },
      ],
    },
    {
      label: "Operations",
    },
    {
      title: "Documents",
      url: "/documents",
      icon: FileText,
    },
    {
      title: "HR Helpdesk",
      url: "/helpdesk",
      icon: Headset,
    },
    {
      title: "Reports & Analytics",
      url: "/reports",
      icon: BarChart3,
    },
    {
      title: "Announcements",
      url: "/announcements",
      icon: Megaphone,
    },
    {
      title: "Approvals",
      url: "/approvals",
      icon: CheckSquare,
    },
    {
      label: "System",
    },
    {
      title: "Settings",
      url: "/settings",
      icon: Settings,
    },
  ],
};
